//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LightSwitchApplication", "OrdenMant_Pedido", "Pedido", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Pedido), "OrdenMant", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.OrdenMant), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "OrdenMant_Componente", "Componente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Componente), "OrdenMant", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.OrdenMant), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "OrdenMant_Lab", "Lab", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Lab), "OrdenMant", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.OrdenMant), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "OrdenMant_Tecnico", "Tecnico", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Tecnico), "OrdenMant", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.OrdenMant), true)]

#endregion

namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApplicationData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApplicationData object using the connection string found in the 'ApplicationData' section of the application configuration file.
        /// </summary>
        public ApplicationData() : base("name=ApplicationData", "ApplicationData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        public ApplicationData(string connectionString) : base(connectionString, "ApplicationData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        public ApplicationData(EntityConnection connection) : base(connection, "ApplicationData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Componente> Componentes
        {
            get
            {
                if ((_Componentes == null))
                {
                    _Componentes = base.CreateObjectSet<Componente>("Componentes");
                }
                return _Componentes;
            }
        }
        private ObjectSet<Componente> _Componentes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lab> Labs
        {
            get
            {
                if ((_Labs == null))
                {
                    _Labs = base.CreateObjectSet<Lab>("Labs");
                }
                return _Labs;
            }
        }
        private ObjectSet<Lab> _Labs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrdenMant> OrdenMants
        {
            get
            {
                if ((_OrdenMants == null))
                {
                    _OrdenMants = base.CreateObjectSet<OrdenMant>("OrdenMants");
                }
                return _OrdenMants;
            }
        }
        private ObjectSet<OrdenMant> _OrdenMants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pedido> Pedidoes
        {
            get
            {
                if ((_Pedidoes == null))
                {
                    _Pedidoes = base.CreateObjectSet<Pedido>("Pedidoes");
                }
                return _Pedidoes;
            }
        }
        private ObjectSet<Pedido> _Pedidoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tecnico> Tecnicoes
        {
            get
            {
                if ((_Tecnicoes == null))
                {
                    _Tecnicoes = base.CreateObjectSet<Tecnico>("Tecnicoes");
                }
                return _Tecnicoes;
            }
        }
        private ObjectSet<Tecnico> _Tecnicoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Componentes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComponentes(Componente componente)
        {
            base.AddObject("Componentes", componente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Labs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLabs(Lab lab)
        {
            base.AddObject("Labs", lab);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrdenMants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrdenMants(OrdenMant ordenMant)
        {
            base.AddObject("OrdenMants", ordenMant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pedidoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPedidoes(Pedido pedido)
        {
            base.AddObject("Pedidoes", pedido);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tecnicoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTecnicoes(Tecnico tecnico)
        {
            base.AddObject("Tecnicoes", tecnico);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Componente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Componente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Componente object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static Componente CreateComponente(global::System.Int32 id, global::System.String nombre, global::System.String codigo, global::System.Int16 tipo, global::System.Byte[] rowVersion)
        {
            Componente componente = new Componente();
            componente.Id = id;
            componente.nombre = nombre;
            componente.codigo = codigo;
            componente.tipo = tipo;
            componente.RowVersion = rowVersion;
            return componente;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = value;
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = value;
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = value;
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.Int16 _tipo;
        partial void OntipoChanging(global::System.Int16 value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "OrdenMant_Componente", "OrdenMant")]
        public EntityCollection<OrdenMant> OrdenMant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrdenMant>("LightSwitchApplication.OrdenMant_Componente", "OrdenMant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrdenMant>("LightSwitchApplication.OrdenMant_Componente", "OrdenMant", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Lab")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lab : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lab object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="cantPc">Initial value of the CantPc property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static Lab CreateLab(global::System.Int32 id, global::System.Int32 cantPc, global::System.String nombre, global::System.Byte[] rowVersion)
        {
            Lab lab = new Lab();
            lab.Id = id;
            lab.CantPc = cantPc;
            lab.nombre = nombre;
            lab.RowVersion = rowVersion;
            return lab;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CantPc
        {
            get
            {
                return _CantPc;
            }
            set
            {
                OnCantPcChanging(value);
                ReportPropertyChanging("CantPc");
                _CantPc = value;
                ReportPropertyChanged("CantPc");
                OnCantPcChanged();
            }
        }
        private global::System.Int32 _CantPc;
        partial void OnCantPcChanging(global::System.Int32 value);
        partial void OnCantPcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = value;
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "OrdenMant_Lab", "OrdenMant")]
        public EntityCollection<OrdenMant> OrdenMant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrdenMant>("LightSwitchApplication.OrdenMant_Lab", "OrdenMant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrdenMant>("LightSwitchApplication.OrdenMant_Lab", "OrdenMant", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="OrdenMant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrdenMant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrdenMant object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ordenMant_Pedido">Initial value of the OrdenMant_Pedido property.</param>
        /// <param name="ordenMant_Componente">Initial value of the OrdenMant_Componente property.</param>
        /// <param name="ordenMant_Tecnico">Initial value of the OrdenMant_Tecnico property.</param>
        /// <param name="ordenMant_Lab">Initial value of the OrdenMant_Lab property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static OrdenMant CreateOrdenMant(global::System.Int32 id, global::System.Int32 ordenMant_Pedido, global::System.Int32 ordenMant_Componente, global::System.Int32 ordenMant_Tecnico, global::System.Int32 ordenMant_Lab, global::System.Byte[] rowVersion)
        {
            OrdenMant ordenMant = new OrdenMant();
            ordenMant.Id = id;
            ordenMant.OrdenMant_Pedido = ordenMant_Pedido;
            ordenMant.OrdenMant_Componente = ordenMant_Componente;
            ordenMant.OrdenMant_Tecnico = ordenMant_Tecnico;
            ordenMant.OrdenMant_Lab = ordenMant_Lab;
            ordenMant.RowVersion = rowVersion;
            return ordenMant;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrdenMant_Pedido
        {
            get
            {
                return _OrdenMant_Pedido;
            }
            set
            {
                OnOrdenMant_PedidoChanging(value);
                ReportPropertyChanging("OrdenMant_Pedido");
                _OrdenMant_Pedido = value;
                ReportPropertyChanged("OrdenMant_Pedido");
                OnOrdenMant_PedidoChanged();
            }
        }
        private global::System.Int32 _OrdenMant_Pedido;
        partial void OnOrdenMant_PedidoChanging(global::System.Int32 value);
        partial void OnOrdenMant_PedidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrdenMant_Componente
        {
            get
            {
                return _OrdenMant_Componente;
            }
            set
            {
                OnOrdenMant_ComponenteChanging(value);
                ReportPropertyChanging("OrdenMant_Componente");
                _OrdenMant_Componente = value;
                ReportPropertyChanged("OrdenMant_Componente");
                OnOrdenMant_ComponenteChanged();
            }
        }
        private global::System.Int32 _OrdenMant_Componente;
        partial void OnOrdenMant_ComponenteChanging(global::System.Int32 value);
        partial void OnOrdenMant_ComponenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrdenMant_Tecnico
        {
            get
            {
                return _OrdenMant_Tecnico;
            }
            set
            {
                OnOrdenMant_TecnicoChanging(value);
                ReportPropertyChanging("OrdenMant_Tecnico");
                _OrdenMant_Tecnico = value;
                ReportPropertyChanged("OrdenMant_Tecnico");
                OnOrdenMant_TecnicoChanged();
            }
        }
        private global::System.Int32 _OrdenMant_Tecnico;
        partial void OnOrdenMant_TecnicoChanging(global::System.Int32 value);
        partial void OnOrdenMant_TecnicoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrdenMant_Lab
        {
            get
            {
                return _OrdenMant_Lab;
            }
            set
            {
                OnOrdenMant_LabChanging(value);
                ReportPropertyChanging("OrdenMant_Lab");
                _OrdenMant_Lab = value;
                ReportPropertyChanged("OrdenMant_Lab");
                OnOrdenMant_LabChanged();
            }
        }
        private global::System.Int32 _OrdenMant_Lab;
        partial void OnOrdenMant_LabChanging(global::System.Int32 value);
        partial void OnOrdenMant_LabChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "OrdenMant_Pedido", "Pedido")]
        public Pedido Pedidoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedido>("LightSwitchApplication.OrdenMant_Pedido", "Pedido").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedido>("LightSwitchApplication.OrdenMant_Pedido", "Pedido").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pedido> PedidoesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedido>("LightSwitchApplication.OrdenMant_Pedido", "Pedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pedido>("LightSwitchApplication.OrdenMant_Pedido", "Pedido", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "OrdenMant_Componente", "Componente")]
        public Componente Componentes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Componente>("LightSwitchApplication.OrdenMant_Componente", "Componente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Componente>("LightSwitchApplication.OrdenMant_Componente", "Componente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Componente> ComponentesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Componente>("LightSwitchApplication.OrdenMant_Componente", "Componente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Componente>("LightSwitchApplication.OrdenMant_Componente", "Componente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "OrdenMant_Tecnico", "Tecnico")]
        public Tecnico Tecnico
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tecnico>("LightSwitchApplication.OrdenMant_Tecnico", "Tecnico").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tecnico>("LightSwitchApplication.OrdenMant_Tecnico", "Tecnico").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tecnico> TecnicoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tecnico>("LightSwitchApplication.OrdenMant_Tecnico", "Tecnico");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tecnico>("LightSwitchApplication.OrdenMant_Tecnico", "Tecnico", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "OrdenMant_Lab", "Lab")]
        public Lab Labs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lab>("LightSwitchApplication.OrdenMant_Lab", "Lab").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lab>("LightSwitchApplication.OrdenMant_Lab", "Lab").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Lab> LabsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lab>("LightSwitchApplication.OrdenMant_Lab", "Lab");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Lab>("LightSwitchApplication.OrdenMant_Lab", "Lab", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Pedido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pedido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pedido object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombreSolic">Initial value of the NombreSolic property.</param>
        /// <param name="cantPC">Initial value of the CantPC property.</param>
        /// <param name="cantLabs">Initial value of the CantLabs property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static Pedido CreatePedido(global::System.Int32 id, global::System.String nombreSolic, global::System.Int32 cantPC, global::System.Int32 cantLabs, global::System.Byte[] rowVersion)
        {
            Pedido pedido = new Pedido();
            pedido.Id = id;
            pedido.NombreSolic = nombreSolic;
            pedido.CantPC = cantPC;
            pedido.CantLabs = cantLabs;
            pedido.RowVersion = rowVersion;
            return pedido;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreSolic
        {
            get
            {
                return _NombreSolic;
            }
            set
            {
                OnNombreSolicChanging(value);
                ReportPropertyChanging("NombreSolic");
                _NombreSolic = value;
                ReportPropertyChanged("NombreSolic");
                OnNombreSolicChanged();
            }
        }
        private global::System.String _NombreSolic;
        partial void OnNombreSolicChanging(global::System.String value);
        partial void OnNombreSolicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CantPC
        {
            get
            {
                return _CantPC;
            }
            set
            {
                OnCantPCChanging(value);
                ReportPropertyChanging("CantPC");
                _CantPC = value;
                ReportPropertyChanged("CantPC");
                OnCantPCChanged();
            }
        }
        private global::System.Int32 _CantPC;
        partial void OnCantPCChanging(global::System.Int32 value);
        partial void OnCantPCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CantLabs
        {
            get
            {
                return _CantLabs;
            }
            set
            {
                OnCantLabsChanging(value);
                ReportPropertyChanging("CantLabs");
                _CantLabs = value;
                ReportPropertyChanged("CantLabs");
                OnCantLabsChanged();
            }
        }
        private global::System.Int32 _CantLabs;
        partial void OnCantLabsChanging(global::System.Int32 value);
        partial void OnCantLabsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String software
        {
            get
            {
                return _software;
            }
            set
            {
                OnsoftwareChanging(value);
                ReportPropertyChanging("software");
                _software = value;
                ReportPropertyChanged("software");
                OnsoftwareChanged();
            }
        }
        private global::System.String _software;
        partial void OnsoftwareChanging(global::System.String value);
        partial void OnsoftwareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "OrdenMant_Pedido", "OrdenMant")]
        public EntityCollection<OrdenMant> Ordenmant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrdenMant>("LightSwitchApplication.OrdenMant_Pedido", "OrdenMant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrdenMant>("LightSwitchApplication.OrdenMant_Pedido", "OrdenMant", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Tecnico")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tecnico : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tecnico object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="legajo">Initial value of the Legajo property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static Tecnico CreateTecnico(global::System.Int32 id, global::System.String nombre, global::System.String legajo, global::System.String apellido, global::System.Byte[] rowVersion)
        {
            Tecnico tecnico = new Tecnico();
            tecnico.Id = id;
            tecnico.Nombre = nombre;
            tecnico.Legajo = legajo;
            tecnico.Apellido = apellido;
            tecnico.RowVersion = rowVersion;
            return tecnico;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = value;
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Legajo
        {
            get
            {
                return _Legajo;
            }
            set
            {
                OnLegajoChanging(value);
                ReportPropertyChanging("Legajo");
                _Legajo = value;
                ReportPropertyChanged("Legajo");
                OnLegajoChanged();
            }
        }
        private global::System.String _Legajo;
        partial void OnLegajoChanging(global::System.String value);
        partial void OnLegajoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = value;
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "OrdenMant_Tecnico", "OrdenMant")]
        public EntityCollection<OrdenMant> OrdenMants
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrdenMant>("LightSwitchApplication.OrdenMant_Tecnico", "OrdenMant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrdenMant>("LightSwitchApplication.OrdenMant_Tecnico", "OrdenMant", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
