

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Pedido : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Pedido entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Pedido()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Pedido(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Pedido> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Pedido.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Pedido_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Pedido_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Pedido.DetailsClass.SetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string NombreSolic
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.NombreSolic);
            }
            set
            {
                global::LightSwitchApplication.Pedido.DetailsClass.SetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.NombreSolic, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NombreSolic_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NombreSolic_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NombreSolic_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int CantPC
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.CantPC);
            }
            set
            {
                global::LightSwitchApplication.Pedido.DetailsClass.SetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.CantPC, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CantPC_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CantPC_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CantPC_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int CantLabs
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.CantLabs);
            }
            set
            {
                global::LightSwitchApplication.Pedido.DetailsClass.SetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.CantLabs, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CantLabs_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CantLabs_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CantLabs_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string software
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.software);
            }
            set
            {
                global::LightSwitchApplication.Pedido.DetailsClass.SetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.software, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void software_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void software_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void software_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Pedido.DetailsClass.SetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.OrdenMant> Ordenmant
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetValue(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Ordenmant);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.OrdenMant> OrdenmantQuery
        {
            get
            {
                return global::LightSwitchApplication.Pedido.DetailsClass.GetQuery(this, global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Ordenmant);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Pedido,
                global::LightSwitchApplication.Pedido.DetailsClass,
                global::LightSwitchApplication.Pedido.DetailsClass.IImplementation,
                global::LightSwitchApplication.Pedido.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass>.Entry
                __PedidoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass>.Entry(
                    global::LightSwitchApplication.Pedido.DetailsClass.__Pedido_CreateNew,
                    global::LightSwitchApplication.Pedido.DetailsClass.__Pedido_Created,
                    global::LightSwitchApplication.Pedido.DetailsClass.__Pedido_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Pedido __Pedido_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Pedido> es)
            {
                return new global::LightSwitchApplication.Pedido(es);
            }
            private static void __Pedido_Created(global::LightSwitchApplication.Pedido e)
            {
                e.Pedido_Created();
            }
            private static bool __Pedido_AllowSaveWithErrors(global::LightSwitchApplication.Pedido e)
            {
                bool result = false;
                e.Pedido_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Pedido.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string> NombreSolic
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.NombreSolic) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int> CantPC
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.CantPC) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int> CantLabs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.CantLabs) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string> software
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.software) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::LightSwitchApplication.OrdenMant> Ordenmant
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Ordenmant) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::LightSwitchApplication.OrdenMant>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string NombreSolic { get; set; }
                new int CantPC { get; set; }
                new int CantLabs { get; set; }
                new string software { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable Ordenmant { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Entry
                    NombreSolic = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Entry(
                        "NombreSolic",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._NombreSolic_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._NombreSolic_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._NombreSolic_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._NombreSolic_GetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._NombreSolic_SetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._NombreSolic_OnValueChanged);
                private static void _NombreSolic_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._NombreSolic, sf);
                }
                private static bool _NombreSolic_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.NombreSolic_IsReadOnly(ref result);
                    return result;
                }
                private static void _NombreSolic_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NombreSolic_Validate(r);
                }
                private static string _NombreSolic_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.NombreSolic;
                }
                private static void _NombreSolic_SetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d, string v)
                {
                    d.ImplementationEntity.NombreSolic = v;
                }
                private static void _NombreSolic_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.NombreSolic_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Entry
                    CantPC = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Entry(
                        "CantPC",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantPC_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantPC_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantPC_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantPC_GetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantPC_SetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantPC_OnValueChanged);
                private static void _CantPC_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._CantPC, sf);
                }
                private static bool _CantPC_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.CantPC_IsReadOnly(ref result);
                    return result;
                }
                private static void _CantPC_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CantPC_Validate(r);
                }
                private static int _CantPC_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.CantPC;
                }
                private static void _CantPC_SetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d, int v)
                {
                    d.ImplementationEntity.CantPC = v;
                }
                private static void _CantPC_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.CantPC_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Entry
                    CantLabs = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Entry(
                        "CantLabs",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantLabs_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantLabs_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantLabs_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantLabs_GetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantLabs_SetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CantLabs_OnValueChanged);
                private static void _CantLabs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._CantLabs, sf);
                }
                private static bool _CantLabs_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.CantLabs_IsReadOnly(ref result);
                    return result;
                }
                private static void _CantLabs_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CantLabs_Validate(r);
                }
                private static int _CantLabs_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.CantLabs;
                }
                private static void _CantLabs_SetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d, int v)
                {
                    d.ImplementationEntity.CantLabs = v;
                }
                private static void _CantLabs_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.CantLabs_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Entry
                    software = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Entry(
                        "software",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._software_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._software_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._software_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._software_GetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._software_SetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._software_OnValueChanged);
                private static void _software_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._software, sf);
                }
                private static bool _software_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.software_IsReadOnly(ref result);
                    return result;
                }
                private static void _software_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.software_Validate(r);
                }
                private static string _software_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.software;
                }
                private static void _software_SetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d, string v)
                {
                    d.ImplementationEntity.software = v;
                }
                private static void _software_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.software_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Pedido e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Pedido e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Pedido.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Pedido e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::LightSwitchApplication.OrdenMant>.Entry
                    Ordenmant = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::LightSwitchApplication.OrdenMant>.Entry(
                        "Ordenmant",
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Ordenmant_Stub,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Ordenmant_GetReferencedEntities,
                        global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties._Ordenmant_GetEntityCollection);
                private static void _Ordenmant_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pedido.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::LightSwitchApplication.OrdenMant>.Data> c, global::LightSwitchApplication.Pedido.DetailsClass d, object sf)
                {
                    c(d, ref d._Ordenmant, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.OrdenMant> _Ordenmant_GetReferencedEntities(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.OrdenMant, global::LightSwitchApplication.OrdenMant.DetailsClass>(global::LightSwitchApplication.Pedido.DetailsClass.PropertySetProperties.Ordenmant, ref d._Ordenmant);
                }
                private static global::System.Collections.IEnumerable _Ordenmant_GetEntityCollection(global::LightSwitchApplication.Pedido.DetailsClass d)
                {
                    return d.ImplementationEntity.Ordenmant;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Data _NombreSolic;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Data _CantPC;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, int>.Data _CantLabs;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Data _software;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Pedido, global::LightSwitchApplication.Pedido.DetailsClass, global::LightSwitchApplication.OrdenMant>.Data _Ordenmant;
            
        }
    
        #endregion
    }
    
    #endregion
}
