//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/16/2017 3:25:06 PM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationData in the schema.
    /// </summary>
    public partial class ApplicationData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Componentes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Componente> Componentes
        {
            get
            {
                if ((this._Componentes == null))
                {
                    this._Componentes = base.CreateQuery<Componente>("Componentes");
                }
                return this._Componentes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Componente> _Componentes;
        /// <summary>
        /// There are no comments for Labs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Lab> Labs
        {
            get
            {
                if ((this._Labs == null))
                {
                    this._Labs = base.CreateQuery<Lab>("Labs");
                }
                return this._Labs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Lab> _Labs;
        /// <summary>
        /// There are no comments for OrdenMants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<OrdenMant> OrdenMants
        {
            get
            {
                if ((this._OrdenMants == null))
                {
                    this._OrdenMants = base.CreateQuery<OrdenMant>("OrdenMants");
                }
                return this._OrdenMants;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<OrdenMant> _OrdenMants;
        /// <summary>
        /// There are no comments for Pedidoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Pedido> Pedidoes
        {
            get
            {
                if ((this._Pedidoes == null))
                {
                    this._Pedidoes = base.CreateQuery<Pedido>("Pedidoes");
                }
                return this._Pedidoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Pedido> _Pedidoes;
        /// <summary>
        /// There are no comments for Tecnicoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Tecnico> Tecnicoes
        {
            get
            {
                if ((this._Tecnicoes == null))
                {
                    this._Tecnicoes = base.CreateQuery<Tecnico>("Tecnicoes");
                }
                return this._Tecnicoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Tecnico> _Tecnicoes;
        /// <summary>
        /// There are no comments for Componentes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToComponentes(Componente componente)
        {
            base.AddObject("Componentes", componente);
        }
        /// <summary>
        /// There are no comments for Labs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLabs(Lab lab)
        {
            base.AddObject("Labs", lab);
        }
        /// <summary>
        /// There are no comments for OrdenMants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrdenMants(OrdenMant ordenMant)
        {
            base.AddObject("OrdenMants", ordenMant);
        }
        /// <summary>
        /// There are no comments for Pedidoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPedidoes(Pedido pedido)
        {
            base.AddObject("Pedidoes", pedido);
        }
        /// <summary>
        /// There are no comments for Tecnicoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTecnicoes(Tecnico tecnico)
        {
            base.AddObject("Tecnicoes", tecnico);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"Componente\"><Key><PropertyRef Name=\"Id\" /></Ke" +
                "y><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGenerate" +
                "dPattern=\"Identity\" /><Property Name=\"nombre\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"255\" /><Property Name=\"codigo\" Type=\"Edm.String\" Nullable=\"false\" Ma" +
                "xLength=\"255\" /><Property Name=\"tipo\" Type=\"Edm.Int16\" Nullable=\"false\" /><Prope" +
                "rty Name=\"OrdenMant_Componente\" Type=\"Edm.Int32\" /><Property Name=\"CreatedBy\" Ty" +
                "pe=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOff" +
                "set\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property" +
                " Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"E" +
                "dm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPat" +
                "tern=\"Computed\" /><NavigationProperty Name=\"OrdenMant\" Relationship=\"LightSwitch" +
                "Application.OrdenMant_Componente\" ToRole=\"OrdenMant\" FromRole=\"Componente\" /></E" +
                "ntityType><EntityType Name=\"Lab\"><Key><PropertyRef Name=\"Id\" /></Key><Property N" +
                "ame=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Ide" +
                "ntity\" /><Property Name=\"CantPc\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property N" +
                "ame=\"nombre\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name" +
                "=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"" +
                "Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"2" +
                "55\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowV" +
                "ersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:St" +
                "oreGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"OrdenMant\" Relationsh" +
                "ip=\"LightSwitchApplication.OrdenMant_Lab\" ToRole=\"OrdenMant\" FromRole=\"Lab\" /></" +
                "EntityType><EntityType Name=\"OrdenMant\"><Key><PropertyRef Name=\"Id\" /></Key><Pro" +
                "perty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPatte" +
                "rn=\"Identity\" /><Property Name=\"OrdenMant_Pedido\" Type=\"Edm.Int32\" Nullable=\"fal" +
                "se\" /><Property Name=\"OrdenMant_Tecnico\" Type=\"Edm.Int32\" Nullable=\"false\" /><Pr" +
                "operty Name=\"OrdenMant_Lab\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"" +
                "CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Ed" +
                "m.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255" +
                "\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVer" +
                "sion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:Stor" +
                "eGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"Pedidoes\" Relationship=" +
                "\"LightSwitchApplication.OrdenMant_Pedido\" ToRole=\"Pedido\" FromRole=\"OrdenMant\" /" +
                "><NavigationProperty Name=\"Componentes\" Relationship=\"LightSwitchApplication.Ord" +
                "enMant_Componente\" ToRole=\"Componente\" FromRole=\"OrdenMant\" /><NavigationPropert" +
                "y Name=\"Tecnico\" Relationship=\"LightSwitchApplication.OrdenMant_Tecnico\" ToRole=" +
                "\"Tecnico\" FromRole=\"OrdenMant\" /><NavigationProperty Name=\"Labs\" Relationship=\"L" +
                "ightSwitchApplication.OrdenMant_Lab\" ToRole=\"Lab\" FromRole=\"OrdenMant\" /></Entit" +
                "yType><EntityType Name=\"Pedido\"><Key><PropertyRef Name=\"Id\" /></Key><Property Na" +
                "me=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Iden" +
                "tity\" /><Property Name=\"NombreSolic\" Type=\"Edm.String\" Nullable=\"false\" MaxLengt" +
                "h=\"255\" /><Property Name=\"CantPC\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property " +
                "Name=\"CantLabs\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"software\" Ty" +
                "pe=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\" M" +
                "axLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Property " +
                "Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modified\" " +
                "Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullab" +
                "le=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\" /" +
                "><NavigationProperty Name=\"Ordenmant\" Relationship=\"LightSwitchApplication.Orden" +
                "Mant_Pedido\" ToRole=\"OrdenMant\" FromRole=\"Pedido\" /></EntityType><EntityType Nam" +
                "e=\"Tecnico\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.In" +
                "t32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" /><Property Na" +
                "me=\"Nombre\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=" +
                "\"Legajo\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"Ap" +
                "ellido\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"Cre" +
                "atedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.D" +
                "ateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /" +
                "><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersio" +
                "n\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGe" +
                "neratedPattern=\"Computed\" /><NavigationProperty Name=\"OrdenMants\" Relationship=\"" +
                "LightSwitchApplication.OrdenMant_Tecnico\" ToRole=\"OrdenMant\" FromRole=\"Tecnico\" " +
                "/></EntityType><Association Name=\"OrdenMant_Pedido\"><End Role=\"Pedido\" Type=\"Lig" +
                "htSwitchApplication.Pedido\" Multiplicity=\"1\" /><End Role=\"OrdenMant\" Type=\"Light" +
                "SwitchApplication.OrdenMant\" Multiplicity=\"*\" /><ReferentialConstraint><Principa" +
                "l Role=\"Pedido\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"OrdenMant\"" +
                "><PropertyRef Name=\"OrdenMant_Pedido\" /></Dependent></ReferentialConstraint></As" +
                "sociation><Association Name=\"OrdenMant_Componente\"><End Role=\"OrdenMant\" Type=\"L" +
                "ightSwitchApplication.OrdenMant\" Multiplicity=\"0..1\" /><End Role=\"Componente\" Ty" +
                "pe=\"LightSwitchApplication.Componente\" Multiplicity=\"*\" /><ReferentialConstraint" +
                "><Principal Role=\"OrdenMant\"><PropertyRef Name=\"Id\" /></Principal><Dependent Rol" +
                "e=\"Componente\"><PropertyRef Name=\"OrdenMant_Componente\" /></Dependent></Referent" +
                "ialConstraint></Association><Association Name=\"OrdenMant_Lab\"><End Role=\"Lab\" Ty" +
                "pe=\"LightSwitchApplication.Lab\" Multiplicity=\"1\" /><End Role=\"OrdenMant\" Type=\"L" +
                "ightSwitchApplication.OrdenMant\" Multiplicity=\"*\" /><ReferentialConstraint><Prin" +
                "cipal Role=\"Lab\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"OrdenMant" +
                "\"><PropertyRef Name=\"OrdenMant_Lab\" /></Dependent></ReferentialConstraint></Asso" +
                "ciation><Association Name=\"OrdenMant_Tecnico\"><End Role=\"Tecnico\" Type=\"LightSwi" +
                "tchApplication.Tecnico\" Multiplicity=\"1\" /><End Role=\"OrdenMant\" Type=\"LightSwit" +
                "chApplication.OrdenMant\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Ro" +
                "le=\"Tecnico\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"OrdenMant\"><P" +
                "ropertyRef Name=\"OrdenMant_Tecnico\" /></Dependent></ReferentialConstraint></Asso" +
                "ciation><EntityContainer Name=\"ApplicationData\" m:IsDefaultEntityContainer=\"true" +
                "\"><EntitySet Name=\"Componentes\" EntityType=\"LightSwitchApplication.Componente\" /" +
                "><EntitySet Name=\"Labs\" EntityType=\"LightSwitchApplication.Lab\" /><EntitySet Nam" +
                "e=\"OrdenMants\" EntityType=\"LightSwitchApplication.OrdenMant\" /><EntitySet Name=\"" +
                "Pedidoes\" EntityType=\"LightSwitchApplication.Pedido\" /><EntitySet Name=\"Tecnicoe" +
                "s\" EntityType=\"LightSwitchApplication.Tecnico\" /><AssociationSet Name=\"OrdenMant" +
                "_Pedido\" Association=\"LightSwitchApplication.OrdenMant_Pedido\"><End Role=\"Pedido" +
                "\" EntitySet=\"Pedidoes\" /><End Role=\"OrdenMant\" EntitySet=\"O";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = @"rdenMants"" /></AssociationSet><AssociationSet Name=""OrdenMant_Componente"" Association=""LightSwitchApplication.OrdenMant_Componente""><End Role=""OrdenMant"" EntitySet=""OrdenMants"" /><End Role=""Componente"" EntitySet=""Componentes"" /></AssociationSet><AssociationSet Name=""OrdenMant_Lab"" Association=""LightSwitchApplication.OrdenMant_Lab""><End Role=""Lab"" EntitySet=""Labs"" /><End Role=""OrdenMant"" EntitySet=""OrdenMants"" /></AssociationSet><AssociationSet Name=""OrdenMant_Tecnico"" Association=""LightSwitchApplication.OrdenMant_Tecnico""><End Role=""Tecnico"" EntitySet=""Tecnicoes"" /><End Role=""OrdenMant"" EntitySet=""OrdenMants"" /></AssociationSet><FunctionImport Name=""Microsoft_LightSwitch_GetCanInformation"" ReturnType=""Edm.String"" m:HttpMethod=""GET""><Parameter Name=""dataServiceMembers"" Type=""Edm.String"" Mode=""In"" /></FunctionImport></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Componente in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Componentes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Componente : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Componente object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nombre">Initial value of nombre.</param>
        /// <param name="codigo">Initial value of codigo.</param>
        /// <param name="tipo">Initial value of tipo.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Componente CreateComponente(int ID, string nombre, string codigo, short tipo, byte[] rowVersion)
        {
            Componente componente = new Componente();
            componente.Id = ID;
            componente.nombre = nombre;
            componente.codigo = codigo;
            componente.tipo = tipo;
            componente.RowVersion = rowVersion;
            return componente;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property nombre in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                this.OnnombreChanging(value);
                if (object.Equals(this.nombre, value))
                {
                    return;
                }
                this._nombre = value;
                this.OnnombreChanged();
                this.OnPropertyChanged("nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nombre;
        partial void OnnombreChanging(string value);
        partial void OnnombreChanged();
        /// <summary>
        /// There are no comments for Property codigo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string codigo
        {
            get
            {
                return this._codigo;
            }
            set
            {
                this.OncodigoChanging(value);
                if (object.Equals(this.codigo, value))
                {
                    return;
                }
                this._codigo = value;
                this.OncodigoChanged();
                this.OnPropertyChanged("codigo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _codigo;
        partial void OncodigoChanging(string value);
        partial void OncodigoChanged();
        /// <summary>
        /// There are no comments for Property tipo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short tipo
        {
            get
            {
                return this._tipo;
            }
            set
            {
                this.OntipoChanging(value);
                if (object.Equals(this.tipo, value))
                {
                    return;
                }
                this._tipo = value;
                this.OntipoChanged();
                this.OnPropertyChanged("tipo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _tipo;
        partial void OntipoChanging(short value);
        partial void OntipoChanged();
        /// <summary>
        /// There are no comments for Property OrdenMant_Componente in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> OrdenMant_Componente
        {
            get
            {
                return this._OrdenMant_Componente;
            }
            set
            {
                this.OnOrdenMant_ComponenteChanging(value);
                if (object.Equals(this.OrdenMant_Componente, value))
                {
                    return;
                }
                this._OrdenMant_Componente = value;
                this.OnOrdenMant_ComponenteChanged();
                this.OnPropertyChanged("OrdenMant_Componente");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _OrdenMant_Componente;
        partial void OnOrdenMant_ComponenteChanging(global::System.Nullable<int> value);
        partial void OnOrdenMant_ComponenteChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for OrdenMant in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public OrdenMant OrdenMant
        {
            get
            {
                this.@__OrdenMant.EnsureValueInitialized();
                return this._OrdenMant;
            }
            set
            {
                OrdenMant previous = this.OrdenMant;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._OrdenMant = null;
                    this.@__OrdenMant.OnValueSet();
                    previous.Componentes.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.OrdenMant_Componente = value.Id;
                    }
                    else
                    {
                        this.OrdenMant_Componente = default(global::System.Nullable<int>);
                    }
                }
                this._OrdenMant = value;
                this.@__OrdenMant.OnValueSet();
                if ((value != null))
                {
                    value.@__Componentes.Add(this);
                }
                this.___OnPropertyChanged("OrdenMant");
                this.OnPropertyChanged("OrdenMant");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private OrdenMant _OrdenMant;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Lab in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Labs")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Lab : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Lab object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="cantPc">Initial value of CantPc.</param>
        /// <param name="nombre">Initial value of nombre.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Lab CreateLab(int ID, int cantPc, string nombre, byte[] rowVersion)
        {
            Lab lab = new Lab();
            lab.Id = ID;
            lab.CantPc = cantPc;
            lab.nombre = nombre;
            lab.RowVersion = rowVersion;
            return lab;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CantPc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CantPc
        {
            get
            {
                return this._CantPc;
            }
            set
            {
                this.OnCantPcChanging(value);
                if (object.Equals(this.CantPc, value))
                {
                    return;
                }
                this._CantPc = value;
                this.OnCantPcChanged();
                this.OnPropertyChanged("CantPc");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CantPc;
        partial void OnCantPcChanging(int value);
        partial void OnCantPcChanged();
        /// <summary>
        /// There are no comments for Property nombre in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                this.OnnombreChanging(value);
                if (object.Equals(this.nombre, value))
                {
                    return;
                }
                this._nombre = value;
                this.OnnombreChanged();
                this.OnPropertyChanged("nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nombre;
        partial void OnnombreChanging(string value);
        partial void OnnombreChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for OrdenMant in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<OrdenMant> OrdenMant
        {
            get
            {
                this.@__OrdenMant.EnsureValueInitialized();
                return this._OrdenMant;
            }
            set
            {
                this._OrdenMant = value;
                this.OnPropertyChanged("OrdenMant");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<OrdenMant> _OrdenMant = new global::System.Data.Services.Client.DataServiceCollection<OrdenMant>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.OrdenMant in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("OrdenMants")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class OrdenMant : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new OrdenMant object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="ordenMant_Pedido">Initial value of OrdenMant_Pedido.</param>
        /// <param name="ordenMant_Tecnico">Initial value of OrdenMant_Tecnico.</param>
        /// <param name="ordenMant_Lab">Initial value of OrdenMant_Lab.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static OrdenMant CreateOrdenMant(int ID, int ordenMant_Pedido, int ordenMant_Tecnico, int ordenMant_Lab, byte[] rowVersion)
        {
            OrdenMant ordenMant = new OrdenMant();
            ordenMant.Id = ID;
            ordenMant.OrdenMant_Pedido = ordenMant_Pedido;
            ordenMant.OrdenMant_Tecnico = ordenMant_Tecnico;
            ordenMant.OrdenMant_Lab = ordenMant_Lab;
            ordenMant.RowVersion = rowVersion;
            return ordenMant;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property OrdenMant_Pedido in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int OrdenMant_Pedido
        {
            get
            {
                return this._OrdenMant_Pedido;
            }
            set
            {
                this.OnOrdenMant_PedidoChanging(value);
                if (object.Equals(this.OrdenMant_Pedido, value))
                {
                    return;
                }
                this._OrdenMant_Pedido = value;
                this.OnOrdenMant_PedidoChanged();
                this.OnPropertyChanged("OrdenMant_Pedido");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _OrdenMant_Pedido;
        partial void OnOrdenMant_PedidoChanging(int value);
        partial void OnOrdenMant_PedidoChanged();
        /// <summary>
        /// There are no comments for Property OrdenMant_Tecnico in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int OrdenMant_Tecnico
        {
            get
            {
                return this._OrdenMant_Tecnico;
            }
            set
            {
                this.OnOrdenMant_TecnicoChanging(value);
                if (object.Equals(this.OrdenMant_Tecnico, value))
                {
                    return;
                }
                this._OrdenMant_Tecnico = value;
                this.OnOrdenMant_TecnicoChanged();
                this.OnPropertyChanged("OrdenMant_Tecnico");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _OrdenMant_Tecnico;
        partial void OnOrdenMant_TecnicoChanging(int value);
        partial void OnOrdenMant_TecnicoChanged();
        /// <summary>
        /// There are no comments for Property OrdenMant_Lab in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int OrdenMant_Lab
        {
            get
            {
                return this._OrdenMant_Lab;
            }
            set
            {
                this.OnOrdenMant_LabChanging(value);
                if (object.Equals(this.OrdenMant_Lab, value))
                {
                    return;
                }
                this._OrdenMant_Lab = value;
                this.OnOrdenMant_LabChanged();
                this.OnPropertyChanged("OrdenMant_Lab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _OrdenMant_Lab;
        partial void OnOrdenMant_LabChanging(int value);
        partial void OnOrdenMant_LabChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Pedidoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Pedido Pedidoes
        {
            get
            {
                this.@__Pedidoes.EnsureValueInitialized();
                return this._Pedidoes;
            }
            set
            {
                Pedido previous = this.Pedidoes;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Pedidoes = null;
                    this.@__Pedidoes.OnValueSet();
                    previous.Ordenmant.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.OrdenMant_Pedido = value.Id;
                    }
                    else
                    {
                        this.OrdenMant_Pedido = default(int);
                    }
                }
                this._Pedidoes = value;
                this.@__Pedidoes.OnValueSet();
                if ((value != null))
                {
                    value.@__Ordenmant.Add(this);
                }
                this.___OnPropertyChanged("Pedidoes");
                this.OnPropertyChanged("Pedidoes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Pedido _Pedidoes;
        /// <summary>
        /// There are no comments for Componentes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Componente> Componentes
        {
            get
            {
                this.@__Componentes.EnsureValueInitialized();
                return this._Componentes;
            }
            set
            {
                this._Componentes = value;
                this.OnPropertyChanged("Componentes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Componente> _Componentes = new global::System.Data.Services.Client.DataServiceCollection<Componente>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Tecnico in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Tecnico Tecnico
        {
            get
            {
                this.@__Tecnico.EnsureValueInitialized();
                return this._Tecnico;
            }
            set
            {
                Tecnico previous = this.Tecnico;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Tecnico = null;
                    this.@__Tecnico.OnValueSet();
                    previous.OrdenMants.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.OrdenMant_Tecnico = value.Id;
                    }
                    else
                    {
                        this.OrdenMant_Tecnico = default(int);
                    }
                }
                this._Tecnico = value;
                this.@__Tecnico.OnValueSet();
                if ((value != null))
                {
                    value.@__OrdenMants.Add(this);
                }
                this.___OnPropertyChanged("Tecnico");
                this.OnPropertyChanged("Tecnico");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Tecnico _Tecnico;
        /// <summary>
        /// There are no comments for Labs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Lab Labs
        {
            get
            {
                this.@__Labs.EnsureValueInitialized();
                return this._Labs;
            }
            set
            {
                Lab previous = this.Labs;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Labs = null;
                    this.@__Labs.OnValueSet();
                    previous.OrdenMant.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.OrdenMant_Lab = value.Id;
                    }
                    else
                    {
                        this.OrdenMant_Lab = default(int);
                    }
                }
                this._Labs = value;
                this.@__Labs.OnValueSet();
                if ((value != null))
                {
                    value.@__OrdenMant.Add(this);
                }
                this.___OnPropertyChanged("Labs");
                this.OnPropertyChanged("Labs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Lab _Labs;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Pedido in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Pedidoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Pedido : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Pedido object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nombreSolic">Initial value of NombreSolic.</param>
        /// <param name="cantPC">Initial value of CantPC.</param>
        /// <param name="cantLabs">Initial value of CantLabs.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Pedido CreatePedido(int ID, string nombreSolic, int cantPC, int cantLabs, byte[] rowVersion)
        {
            Pedido pedido = new Pedido();
            pedido.Id = ID;
            pedido.NombreSolic = nombreSolic;
            pedido.CantPC = cantPC;
            pedido.CantLabs = cantLabs;
            pedido.RowVersion = rowVersion;
            return pedido;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property NombreSolic in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NombreSolic
        {
            get
            {
                return this._NombreSolic;
            }
            set
            {
                this.OnNombreSolicChanging(value);
                if (object.Equals(this.NombreSolic, value))
                {
                    return;
                }
                this._NombreSolic = value;
                this.OnNombreSolicChanged();
                this.OnPropertyChanged("NombreSolic");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NombreSolic;
        partial void OnNombreSolicChanging(string value);
        partial void OnNombreSolicChanged();
        /// <summary>
        /// There are no comments for Property CantPC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CantPC
        {
            get
            {
                return this._CantPC;
            }
            set
            {
                this.OnCantPCChanging(value);
                if (object.Equals(this.CantPC, value))
                {
                    return;
                }
                this._CantPC = value;
                this.OnCantPCChanged();
                this.OnPropertyChanged("CantPC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CantPC;
        partial void OnCantPCChanging(int value);
        partial void OnCantPCChanged();
        /// <summary>
        /// There are no comments for Property CantLabs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CantLabs
        {
            get
            {
                return this._CantLabs;
            }
            set
            {
                this.OnCantLabsChanging(value);
                if (object.Equals(this.CantLabs, value))
                {
                    return;
                }
                this._CantLabs = value;
                this.OnCantLabsChanged();
                this.OnPropertyChanged("CantLabs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CantLabs;
        partial void OnCantLabsChanging(int value);
        partial void OnCantLabsChanged();
        /// <summary>
        /// There are no comments for Property software in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string software
        {
            get
            {
                return this._software;
            }
            set
            {
                this.OnsoftwareChanging(value);
                if (object.Equals(this.software, value))
                {
                    return;
                }
                this._software = value;
                this.OnsoftwareChanged();
                this.OnPropertyChanged("software");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _software;
        partial void OnsoftwareChanging(string value);
        partial void OnsoftwareChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Ordenmant in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<OrdenMant> Ordenmant
        {
            get
            {
                this.@__Ordenmant.EnsureValueInitialized();
                return this._Ordenmant;
            }
            set
            {
                this._Ordenmant = value;
                this.OnPropertyChanged("Ordenmant");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<OrdenMant> _Ordenmant = new global::System.Data.Services.Client.DataServiceCollection<OrdenMant>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Tecnico in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Tecnicoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Tecnico : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Tecnico object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nombre">Initial value of Nombre.</param>
        /// <param name="legajo">Initial value of Legajo.</param>
        /// <param name="apellido">Initial value of Apellido.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Tecnico CreateTecnico(int ID, string nombre, string legajo, string apellido, byte[] rowVersion)
        {
            Tecnico tecnico = new Tecnico();
            tecnico.Id = ID;
            tecnico.Nombre = nombre;
            tecnico.Legajo = legajo;
            tecnico.Apellido = apellido;
            tecnico.RowVersion = rowVersion;
            return tecnico;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Nombre in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                if (object.Equals(this.Nombre, value))
                {
                    return;
                }
                this._Nombre = value;
                this.OnNombreChanged();
                this.OnPropertyChanged("Nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// There are no comments for Property Legajo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Legajo
        {
            get
            {
                return this._Legajo;
            }
            set
            {
                this.OnLegajoChanging(value);
                if (object.Equals(this.Legajo, value))
                {
                    return;
                }
                this._Legajo = value;
                this.OnLegajoChanged();
                this.OnPropertyChanged("Legajo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Legajo;
        partial void OnLegajoChanging(string value);
        partial void OnLegajoChanged();
        /// <summary>
        /// There are no comments for Property Apellido in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Apellido
        {
            get
            {
                return this._Apellido;
            }
            set
            {
                this.OnApellidoChanging(value);
                if (object.Equals(this.Apellido, value))
                {
                    return;
                }
                this._Apellido = value;
                this.OnApellidoChanged();
                this.OnPropertyChanged("Apellido");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Apellido;
        partial void OnApellidoChanging(string value);
        partial void OnApellidoChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for OrdenMants in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<OrdenMant> OrdenMants
        {
            get
            {
                this.@__OrdenMants.EnsureValueInitialized();
                return this._OrdenMants;
            }
            set
            {
                this._OrdenMants = value;
                this.OnPropertyChanged("OrdenMants");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<OrdenMant> _OrdenMants = new global::System.Data.Services.Client.DataServiceCollection<OrdenMant>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
